# Global configuration
title: Ludo's page
tagline: Hopefully interesting things.
description: >-
  A page with hopefully interesting nuggets of information and experiences that come along in my professional and
  non-professional life. Topics include, but are not limited to: C, Python, various assembly variants, toolchains,
  emulators, embedded software, ARM, SPARC, x86. Expect the occasional sidetrack into the space domain.
baseurl: ""
url: "https://lcvisser.github.io"
author:
  name: Ludo Visser
  url: "https://www.github.com/lcvisser"
tags_path: /by-tag/
categories_path: /by-category/
countapi: lcvisser.github.io

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      author: Ludo Visser
      comments: false

# Build settings
remote_theme: "lcvisser/monophase"
plugins:
  - jekyll-seo-tag
