# Global configuration
title: Ludo's page
tagline: Hopefully interesting things.
baseurl: ""
url: "https://lcvisser.github.io"
author:
  name: Ludo Visser
  url: "https://www.github.com/lcvisser"
tags_path: /by-tag/
categories_path: /by-category/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      author: Ludo Visser
      comments: false

# Build settings
remote_theme: "zivhub/monophase"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
